name: test
on:
  push:
    branches:
    - "**"
  pull_request: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: test
      run: go test -race -coverprofile coverage.out -covermode atomic ./...
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.github_token }}
        path-to-profile: coverage.out
        job-number: ${{ strategy.job-index }}
      if: "matrix.os == 'ubuntu-latest'"